### ISSUE TITLE
Support Docker Logs Commands on Edge Dev Container

### ISSUE THREAD

**Issue by stevebus** [Azure/iotedgedev#26] opened 2018-02-26 02:54 UTC
using the docker container install of the tool.
running iotedgedev docker --show-logs gives the following errors  (can't find the 'start' command)

root@c7c5df12a870:/iotedge/edgesolution1# iotedgedev docker --show-logs
Environment Variables loaded from: .env (/iotedge/edgesolution1/.env)

======== PROCESSING CONFIG FILES ========
Expanding 'deployment.template.json' to '.config/deployment.json'
Expanding 'runtime.template.json' to '.config/runtime.json'

sh: 1: start: not found
sh: 1: start: not found
sh: 1: start: not found
sh: 1: start: not found

If you use the conEmu option in the containerized version, you get:

root@c7c5df12a870:/iotedge/edgesolution1# iotedgedev docker --show-logs
Environment Variables loaded from: .env (/iotedge/edgesolution1/.env)

======== PROCESSING CONFIG FILES ========
Expanding 'deployment.template.json' to '.config/deployment.json'
Expanding 'runtime.template.json' to '.config/runtime.json'

unknown shorthand flag: 'n' in -new_console:sV
See 'docker logs --help'.
unknown shorthand flag: 'n' in -new_console:sV
See 'docker logs --help'.
unknown shorthand flag: 'n' in -new_console:sV
See 'docker logs --help'.
unknown shorthand flag: 'n' in -new_console:sV
See 'docker logs --help'.

**Comment by stevebus** [comment] 2018-02-26 03:06
Meant to add a note above that I saw the note about not finding a reliable way to launch a new SSH window.  I assume that means the --show-logs option can't be run from the containerized version?   it mentioned you "must be on your desktop" to run it, but with the containerized option, we haven't installed the iotedgedev tool on our desktops.   chicken and egg :-)

**Comment by konichi3** [comment] 2021-01-09 01:02
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 01:02 UTC
Labels: feature, p1, poachable
