### ISSUE TITLE
Support Deployment Jobs

### ISSUE THREAD

**Issue by drcrook1** [Azure/iotedgedev#4] opened 2018-01-03 22:21 UTC
Currently you support a single device id.  A device tag list for large scale deployments would be good.  It would be great if some form of boolean logic could be applied to the tags.

**Comment by digimaun** [comment] 2018-05-04 18:05
The IoT extension command sub group for @ scale deployments is 'az iot edge deployment ...'. It supports create/show/list/delete/update. When creating a deployment you can specify parameters such as a target condition (scope in which the deployment should apply to), priority (weighted rules in case of conflicts) and label (human management).

The target condition is the key parameter which can be used to apply deployments against any devices with a specific tag or desired property instead of having to implement iterating across devices.

Example usage:

 az iot edge deployment create -c [configuration name] -n [IoTHub Name] --content
        ../mycontent.json -lab '{"key0":"value0", "key1":"value1"}' --target-condition
        "tags.building=9 and tags.environment='test'" --priority 3

**Comment by jongio** [comment] 2018-07-26 21:13
@shizn - Do you think this is required for GA release?

**Comment by shizn** [comment] 2018-07-27 06:33
Yes. That's a P1 for CLI. Assign to @LazarusX.

**Comment by LazarusX** [comment] 2018-07-31 09:43
@jongio Azure CLI supports deployment at scale: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-deploy-monitor-cli

A naive design would be a wrapper around Azure CLI, except that:
* The IoT Hub name can be parsed from connection string in .env
* Build and expand the deployment manifest template
* Load the deployment manifest and wrap it with a `content` key
* Other parameters are passed as CLI parameters.

Let's discuss it in this week's meeting.

**Comment by digimaun** [comment] 2018-08-02 00:39
Just a quick comment...in v0.5+ of the Az CLI IoT extension you don't have to do step 3 of your design there, as in you can provide an object with a root key of ```modulesContent``` or ```moduleContent``` (will get a deprecated message since its v1 schema). Alternatively you can still do what you proposed.

**Comment by konichi3** [comment] 2021-01-09 01:01
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 01:01 UTC
Labels: feature, p1, poachable
