### ISSUE TITLE
NodeJS Module Add Failure in AzDO

### ISSUE THREAD

**Issue by jongio** [Azure/iotedgedev#346] opened 2018-10-25 06:01 UTC
Getting this when running tox inside of an AzDO pipeline.  @LazarusX - I believe you might know how to fix this.  I've tried a bunch of different chmod commands, but nothing seems to work.

```
2018-10-25T04:13:47.5246742Z ============================================
2018-10-25T04:13:47.5246817Z ======== ADDING MODULE NODEJSMODULE ========
2018-10-25T04:13:47.5246869Z ============================================
2018-10-25T04:13:47.5246926Z 
2018-10-25T04:13:47.5246979Z ERROR: Error: /usr/local/lib/node_modules/yo/node_modules/conf/index.js:128
2018-10-25T04:13:47.5247069Z 			throw err;
2018-10-25T04:13:47.5247116Z 			^
2018-10-25T04:13:47.5247155Z 
2018-10-25T04:13:47.5247394Z Error: EACCES: permission denied, open '/root/.config/insight-nodejs/insight-yo.json'
2018-10-25T04:13:47.5247458Z     at Object.fs.openSync (fs.js:646:18)
2018-10-25T04:13:47.5247529Z     at Object.fs.readFileSync (fs.js:551:33)
2018-10-25T04:13:47.5247592Z     at Conf.get store [as store] (/usr/local/lib/node_modules/yo/node_modules/conf/index.js:108:18)
2018-10-25T04:13:47.5247677Z     at Conf.get (/usr/local/lib/node_modules/yo/node_modules/conf/index.js:47:27)
2018-10-25T04:13:47.5248094Z     at Insight.get optOut [as optOut] (/usr/local/lib/node_modules/yo/node_modules/insight/lib/index.js:52:22)
2018-10-25T04:13:47.5248220Z     at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:197:48)
2018-10-25T04:13:47.5248297Z     at Module._compile (module.js:653:30)
2018-10-25T04:13:47.5248369Z     at Object.Module._extensions..js (module.js:664:10)
2018-10-25T04:13:47.5248460Z     at Module.load (module.js:566:32)
2018-10-25T04:13:47.5248788Z     at tryModuleLoad (module.js:506:12)
2018-10-25T04:13:47.5248866Z 
2018-10-25T04:13:47.5255986Z FAILED
```

**Comment by LazarusX** [comment] 2018-10-25 14:47
The root cause is that Yeoman is opinionated and has issue with root users. See my comment in https://github.com/Azure/iotedgedev/issues/312#issuecomment-416521472. I spent quite some time on it last month, but still haven't come up with an elegant fix except modifying Yeoman's logic.

**Comment by blackchoey** [comment] 2019-12-25 06:05
Now all test cases passed. Closing this issue.

**Closed by blackchoey** 2019-12-25 06:05 UTC
