### ISSUE TITLE
iotedgedev init fails if .env file is not already present 

### ISSUE THREAD

**Issue by yorek** [Azure/iotedgedev#191] opened 2018-06-25 15:15 UTC
I've been following the instructions and after executing the 

`iotedgedev init`

command I get the following error:

```
ERROR: Could not backup /home/iotedge/.env to /home/iotedge/.env.backup
ERROR: [Errno 2] No such file or directory: '/home/iotedge/.env'
```

As a workaround, creating a .env file manually, even completely empty, fix the problem.

Of course, an empty .env file doesn't contain the other needed configuration values, so the *correct* workaround is to make a copy of .env.tmp, rename it to .env and then go with the `iotedgedev init` command.

**Comment by LazarusX** [comment] 2018-06-29 05:16
Did you execute the command in a non-empty folder?

**Comment by konichi3** [comment] 2021-01-09 01:09
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 01:09 UTC
Labels: bug, p2
