### ISSUE TITLE
BYPASS_MODULES and ACTIVE_DOCKER_PLATFORMS design refinement

### ISSUE THREAD

**Issue by LazarusX** [Azure/iotedgedev#203] opened 2018-07-20 02:19 UTC
From https://github.com/Azure/iotedgedev/pull/194#pullrequestreview-138368173

@jongio:
> Thought.
The original intention was that in a CI/CD pipeline you'd want to build multiple platforms...but in reality, you are likely going to want to separate out the platforms and have different build agents for different platforms.
>
> We can rethink this.
>
> With BYPASS_MODULES we don't build those even if they are in deployment.json
>
> with ACTIVE_DOCKER_PLATFORMS, we are saying that when building a module we'll build all of those platforms.
>
> Do we want to change that by default build the platform that is referenced in deployment.json and also build any additional DOCKER platforms that are in this setting?
>
> @adashen @LazarusX

Ray:
> The deployment.template.json will be expanded to deployment.json which will be used for the real deployment. If the user targets the solution for a specific platform, he will always make sure that deployment.template.json reflects his intention. For additional platforms, he can update `ACTIVE_DOCKER_PLATFORMS` to include them. That is my assumption for typical usages.
>
> On the other hand, I want to make this tool works as expected out-of-box. We have many existing documentations introducing the usage of deployment.template.json. Say a user targets the solution to platforms except "amd64" such as "windows-amd64". He knows he needs to update the deployement.template.json. If the `ACTIVE_DOCKER_PLATFORMS` variable contains "amd64", he may encounter build errors, which can be confusing. That's my reason of setting its default value as `""`.

Ray:
> In some cases, users may want to build a single module for a specific platform. Maybe we can add a new command like `iotedgedev buildmodule --name filtermodule --platform arm32v7`?

**Comment by konichi3** [comment] 2021-01-09 01:04
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 01:04 UTC
Labels: enhancement
