### ISSUE TITLE
Error while trying to load extension

### ISSUE THREAD

**Issue by jongio** [Azure/iotedgedev#19] opened 2018-02-11 06:01 UTC
![image](https://user-images.githubusercontent.com/2163001/36070381-db1b48ca-0ead-11e8-9ed6-9abcd0a0e03e.png)

**Comment by jonbgallant** [comment] 2018-02-11 07:05
This doesn't stop the script from continuing, so I think it is a false negative.

**Comment by jonbgallant** [comment] 2018-02-11 07:07
I'm only seeing this on katacoda: https://www.katacoda.com/jongallant/scenarios/iotedgedev-intro

**Comment by jonbgallant** [comment] 2018-04-05 07:12
Seeing on ubuntu vm on azure as well: 
![image](https://user-images.githubusercontent.com/2163001/38351798-0dca1d74-38ec-11e8-8cd2-c76ea8280f28.png)

**Comment by konichi3** [comment] 2021-01-09 01:02
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 01:02 UTC
Labels: bug, p2, poachable
