### ISSUE TITLE
Does azure --setup prompt for a resource group location too early?

### ISSUE THREAD

**Issue by druttka** [Azure/iotedgedev#183] opened 2018-06-08 23:45 UTC
In my experience today, the prompt for resource group location comes immediately after choosing a subscription. After choosing a location, the list of existing resource groups is presented, and I choose one of those, making the region selection irrelevant. Should the RG Location prompt only happen if creating a new RG?

**Comment by jongio** [comment] 2018-06-08 23:46
Yes, I agree.  It goes in order of what is required first.  We need to figure out a way to fork the logic

**Comment by konichi3** [comment] 2021-01-09 01:10
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 01:10 UTC
Labels: enhancement
