### ISSUE TITLE
Selecting Azure Subscription should be done by enumeration rather than name or GUID

### ISSUE THREAD

**Issue by WilliamBerryiii** [Azure/iotedgedev#146] opened 2018-04-04 05:19 UTC
The subscription selection process is error prone in Powershell with occasionally weird copy paste behavior.  It would be nice if the select subscription action used an enumeration such that the user could just pick `1` or `2` as the option.

**Comment by konichi3** [comment] 2021-01-09 01:09
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 01:09 UTC
Labels: enhancement
