### ISSUE TITLE
Init command's Resource Group Loc entry doesn't allow for selection options to be displayed.

### ISSUE THREAD

**Issue by WilliamBerryiii** [Azure/iotedgedev#147] opened 2018-04-04 05:23 UTC
It would be nice if the Resource Group command during init prefetched the users RG locations and presented them as an enumeration to select from.

**Comment by jonbgallant** [comment] 2018-04-04 05:25
The issue is that there are so many locations...it's a big screen dump to list them all.  Will think about it.

**Comment by konichi3** [comment] 2021-01-09 01:09
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 01:09 UTC
Labels: enhancement, p2
