### ISSUE TITLE
Check for yeoman and generator before generating assets

### ISSUE THREAD

**Issue by codefoster** [Azure/iotedgedev#298] opened 2018-08-22 20:08 UTC
If I do `iotedgedev new . --module module1 --template nodejs` and don't have yeoman installed, the tool does not discover that until it's already generated the base project assets. Perhaps we should check for yeoman and for the correct generator before generating assets so we don't get a partially generated project.

**Comment by konichi3** [comment] 2021-01-09 01:13
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 01:13 UTC
Labels: enhancement, p2

**Comment by codefoster** [comment] 2021-01-10 02:40
Not blocking. Thanks.

jf
