### ISSUE TITLE
Update wiki to make sure IoT Edge Dev Container instructions work on Windows container

### ISSUE THREAD

**Issue by LazarusX** [Azure/iotedgedev#261] opened 2018-08-16 08:41 UTC

**Comment by rgamage** [comment] 2020-08-25 16:31
Is there any update on this issue?  Current Wiki instructions make no mention of the fact that you need to be using Linux containers , apparently, because the commands fail when running windows containers.  Instructions for setting up a shared folder/drive are also missing (link to docker article is no help, because there are no instructions on what drive to map to, etc.), and also doesn't work with Windows containers, because the Advanced -> File Sharing menu in Docker Settings is not there.  Please add guidance to clarify all of this.

**Comment by konichi3** [comment] 2021-01-09 01:14
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 01:14 UTC
Labels: p1
