### ISSUE TITLE
Mix of Windows and Linux Containers for .env?

### ISSUE THREAD

**Issue by drcrook1** [Azure/iotedgedev#3] opened 2018-01-03 22:19 UTC
Some containers are linux based, some are windows.  Any possibility of getting a heterogeneous ecosystem supported?

**Comment by jonbgallant** [comment] 2018-01-11 20:43
Is this more about Windows vs Linux or X86 vs ARM?

**Comment by konichi3** [comment] 2021-01-09 01:01
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 01:01 UTC
Labels: need more info
